[package]
name = "wns"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = { version = "0.22.0", features = ["secp256k1"] }
solana-program = "1.8.0"
solana-name-service = "0.6.1"
wormhole-anchor-sdk = "1.0.0"
