[package]
name = "wns"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = "0.22.0"
anchor-spl = "0.22.0"
solana-program = "1.8.0"
solana-sdk = "1.7.11"
solana-name-service = "0.6.1" 
wormhole-anchor-sdk = "1.0.0"   
